export const AUTH_ATTEMPTING = 'AUTH_ATTEMPTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILD = 'SIGNUP_FAILD';
export const USER_LOGOUT = 'USER_LOGOUT';
export const PROFILE_FETCHED = 'PROFILE_FETCHED';
export const GET_CARS = 'GET_CARS';